
services:
  nodejs-app:
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile
    container_name: wa-nodejs-app-con
    ports:
      - "8081:8081"
  rust-app:
    build:
      context: ./rust-app
      dockerfile: Dockerfile
    container_name: wa-rust-app-con
    ports:
      - "8082:8082"
    depends_on:
      - nodejs-app



