
[default]
address = "127.0.0.1"
port = 8001
limits.data-form = "2MiB"
template_dir = "templates/"

[default.databases.rusqlite]
url = "file:rusqlite?mode=memory&cache=shared"

[default.databases.sqlx]
url = "db/sqlx/db.sqlite"

[default.databases.diesel]
url = "db/diesel/db.sqlite"
timeout = 10

[default.databases.diesel_mysql]
url = "mysql://user:password@127.0.0.1/database"
